- .github/workflows/cypress.yml
- Procfile.dev
- package.json
Set up Cypress github action
(Used the [foreman Gem](https://github.com/ddollar/foreman) to start the `rails server` and then run the `cypress tests`)
Closes: #12 
Note: 
- Test coverage will be configured in another PR. [(Issue)](https://github.com/Grupo-AFAL/bali-view-components/issues/31)
> Create Cypress github action

- .github/workflows/standardjs.yml
- babel.config.json
- package.json
- yarn.lock
- Installed Standard JS
Closes: #13 
- Created github action for standard
Closes: #14
> Install standard js and setup github action

- README.md
- app/components/bali/delete_link/component.html.erb
- app/components/bali/delete_link/component.rb
- app/components/bali/delete_link/preview.rb
- app/components/bali/hover_card/component.html.erb
- app/components/bali/hover_card/component.rb
- app/components/bali/hover_card/index.js
- app/components/bali/hover_card/index.scss
- app/components/bali/hover_card/preview.rb
- app/components/bali/link/component.html.erb
- app/components/bali/link/component.rb
- app/components/bali/link/index.js
- app/components/bali/link/preview.rb
- app/components/bali/table/component.html.erb
- app/components/bali/table/component.rb
- app/components/bali/table/previews/default.html.erb
- app/javascript/bali/index.js
- app/javascript/bali/utils/domHelpers.js
- config/locales/view_components.en.yml
- config/locales/view_components.es.yml
- package.json
- spec/components/bali/delete_link_spec.rb
- spec/components/bali/hover_card_spec.rb
- spec/components/bali/link_spec.rb
- spec/components/bali/table_spec.rb
- spec/dummy/app/assets/stylesheets/application.scss
- spec/dummy/app/controllers/hovercard_controller.rb
- spec/dummy/app/javascript/application.js
- spec/dummy/config/routes.rb
- yarn.lock
**Objetivo**
Agregar los siguientes componentes:
- `Link`
- `DeleteLink` 
- `HoverCard`
> Agregar `Link`, `DeleteLink` y `HoverCard`

- README.md
- app/components/bali/icon/component.rb
- app/components/bali/icon/index.scss
- app/components/bali/icon/preview.rb
- spec/dummy/app/assets/stylesheets/application.scss
- Added documentation
- Updated previews to `default`, `with_custom_class` and `all_existing_icons`
- Added CSS classes
Closes #66
> Update Icon component

- app/components/bali/icon/index.scss
Fixed icon-component SVG sizes
Update to this PR 
https://github.com/Grupo-AFAL/bali-view-components/pull/79
> Fix icon component css

- app/components/bali/modal/index.scss
**Objetivo**
- Mejorar vista de modal en dispositivos móviles
Pasar de :
A esto:
> Mejorar vista de modal en móvil

- README.md
- spec/components/bali/dropdown_spec.rb
Objetivo:
1. Creación del test de dropdown
2. Actualización de tabla de README con el check del dropdown
> Bali dropdown test

- CHANGELOG.md
- README.md
- app/components/bali/calendar/component.rb
- app/components/bali/calendar/header/component.rb
- app/components/bali/calendar/preview.rb
- app/components/bali/link/component.html.erb
- app/components/bali/link/component.rb
- app/components/bali/link/preview.rb
- app/lib/bali/html_element_helper.rb
- app/lib/bali/path_helper.rb
- spec/components/bali/link_spec.rb
The link component was completed and added documentation to the calendar component.
> Finish link component

- app/components/bali/dropdown/component.html.erb
- app/components/bali/dropdown/component.rb
- app/components/bali/dropdown/preview.rb
Objetivo:
1. Agregar parámetro de align: left, right y center
2. Ajuste de clase necesaria en dropdown-trigger
3. Agregar parámetro align a lookbook
> Agregar caracteristicas adicionales dropdown

- Gemfile.lock
- app/components/bali/dropdown/component.rb
- app/components/bali/dropdown/preview.rb
- lib/bali/version.rb
- package.json
Objetivo:
1. Agregar opciones de alineación: left, right y up
> Cambio de align con 3 opciones en dropdown

- CHANGELOG.md
- Gemfile.lock
- lib/bali.rb
- lib/bali/layout_concern.rb
- lib/bali/version.rb
- package.json
- spec/layout_concern_spec.rb
- Added conditional layout concern to complement the Modal::Component Controller
Closes: https://github.com/Grupo-AFAL/bali-view-components/issues/87
> Add layout concern

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/dropdown/index.scss
- lib/bali/version.rb
- package.json
- spec/dummy/app/assets/stylesheets/application.scss
Added min-width css property to Dropdown::Component
> add min-width to menu of the dropdown component

- CHANGELOG.md
- Gemfile.lock
- lib/bali.rb
- lib/bali/utils.rb
- lib/bali/version.rb
- package.json
- spec/utils_spec.rb
- Added some utils methods from FEH
Closes: https://github.com/Grupo-AFAL/bali-view-components/issues/88
> Add utils methods

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/tabs/component.html.erb
- app/components/bali/tabs/component.rb
- app/components/bali/tabs/index.js
- app/components/bali/tabs/preview.rb
- app/components/bali/tabs/tab/component.rb
- app/components/bali/tabs/trigger/component.html.erb
- app/components/bali/tabs/trigger/component.rb
- lib/bali/version.rb
- package.json
- spec/bali/components/tabs_spec.rb
**Nota:**
- Decidí hacer render del Trigger en el `component.html.erb` del `Tabs`, porque al hacerlo un slot de `Tab` se presentaba el siguiente error en las prueba:
> Permitir hacer Full Page Reload al Dar click a un Tab 

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/side_menu/item/component.html.erb
- app/components/bali/side_menu/item/component.rb
- lib/bali/version.rb
- package.json
Objetivo:
Al seleccionar un sub menu, el principal queda inactivo, con este fix se agrega la clase "is-active" al menu padre del sub menu seleccionado.
> Corrección de menu superior de sidemenu

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/card/component.rb
- lib/bali/version.rb
- package.json
**Objetivo**
- Utilizar `slot` en lugar de `div` para hacer wrap del `image` slot en Card.
> Use slot to wrap image in card

- CHANGELOG.md
- Gemfile.lock
- app/javascript/bali/index.js
- lib/bali/version.rb
- package.json
**Objetivo**
- Exportar `domHelpers`
> Export domHelpers

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/reveal/index.scss
- lib/bali/version.rb
- package.json
**Objetivo**
- Arreglar el siguiente error visual al utilizar íconos en el contenido del reveal component
> Fix issue with icons reveal component

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/page_header/index.scss
- lib/bali/version.rb
- package.json
- spec/dummy/app/assets/stylesheets/application.scss
- Updated the PageHeader::Component to prevent overflow
**Before:**
**After:**
> Prevent PageHeader::Component overflow

- CHANGELOG.md
- Gemfile.lock
- app/javascript/bali/controllers/step-number-input-controller.js
- lib/bali/version.rb
- package.json
**Objetivo**
- Permitir asignar el valor del step en `step number input`
> Custom step in step number input

- CHANGELOG.md
- Gemfile.lock
- README.md
- app/components/bali/chart/component.rb
- app/components/bali/chart/dataset.rb
- app/components/bali/heatmap/component.html.erb
- app/components/bali/heatmap/component.rb
- app/components/bali/heatmap/index.scss
- app/components/bali/heatmap/preview.rb
- app/components/bali/utils/color_picker.rb
- lib/bali/version.rb
- package.json
- spec/bali/components/heatmap_spec.rb
- spec/dummy/app/assets/stylesheets/application.scss
**Objetivo**
- Agregar Heatmap Component
> Add heatmap component

- CHANGELOG.md
- Gemfile.lock
- README.md
- app/components/bali/timeago/component.rb
- app/components/bali/timeago/index.js
- app/components/bali/timeago/preview.rb
- app/javascript/bali/index.js
- lib/bali/version.rb
- package.json
- spec/bali/components/timeago_spec.rb
- spec/dummy/app/javascript/application.js
- yarn.lock
**Objetivo**
- Agregar `Timeago::Component`
> Add timeago component

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/chart/index.js
- lib/bali/version.rb
- package.json
- yarn.lock
**Objetivo**
- Remover dependencia a `stimulus-chart-js`
> Remove chartjs dependency

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/hover_card/index.scss
- lib/bali/version.rb
- package.json
> add less-than-modal class to hide hover-card when is necessary

- CHANGELOG.md
- Gemfile.lock
- app/javascript/bali/controllers/radio-toggle-controller.js
- lib/bali/version.rb
- package.json
Added the ability to accept multiple values in the current value. 
This is to show the same result for multiple radio buttons.
> add multiples values

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/modal/index.js
- lib/bali/version.rb
- package.json
Update `ModalController` to check for targets (Wrapper and Background) existence before attempting action.
> Check for modal targets before acting

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/navbar/index.js
- lib/bali/version.rb
- package.json
**Objetivo**
- Arreglar la funcionalidad de transparencia en el `Navbar`
> Fix navbar transparency

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/filters/controllers/filter-form-controller.js
- app/components/bali/filters/controllers/popup-controller.js
- app/javascript/bali/utils/form.js
- lib/bali/version.rb
- package.json
- Fixes issue where the Back button wasn't working
- Removed `submitForm` function because it manipulated the history. (Recommended way of submitting a form is with `requestSubmit()` function.)
> Dont change the history manually because it interferes with Turbo

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/table/component.html.erb
- app/components/bali/table/component.rb
- lib/bali/version.rb
- package.json
**Objetive**
-  Add an `id` to the `no records` row when the table is empty.
> Added `id` to `no records` row (Table::Component)

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/table/component.rb
- lib/bali/version.rb
- package.json
**Objetivo**
- Arreglar asignación de `id` en `Table::Component`
> Fix id assigment in table component

- CHANGELOG.md
- Gemfile.lock
- README.md
- app/components/bali/progress/component.html.erb
- app/components/bali/progress/component.rb
- app/components/bali/progress/index.scss
- app/components/bali/progress/preview.rb
- lib/bali/version.rb
- package.json
- spec/bali/components/progress_spec.rb
- spec/dummy/app/assets/stylesheets/application.scss
> Create progress component

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/gantt_chart/component.html.erb
- app/components/bali/gantt_chart/component.rb
- app/components/bali/gantt_chart/index.scss
- app/components/bali/gantt_chart/preview.rb
- lib/bali/version.rb
- package.json
Added list footer to gantt chart
List footer with field inside:
> Add list footer to gantt chart

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/link/component.rb
- app/components/bali/notification/component.rb
- app/components/bali/notification/index.scss
- lib/bali.rb
- lib/bali/form_builder/submit_fields.rb
- lib/bali/version.rb
- package.json
**Objective**
- Update `Link`, `Notification` component to support `native apps`
> Update `Link`, `Notification` component to support `native apps`

- CHANGELOG.md
- Gemfile.lock
- README.md
- app/components/bali/hover_card/index.js
- app/components/bali/turbo_native_app/sign_out/component.rb
- app/components/bali/turbo_native_app/sign_out/index.js
- app/components/bali/turbo_native_app/sign_out/preview.rb
- app/javascript/bali/index.js
- config/locales/view_components.en.yml
- config/locales/view_components.es.yml
- lib/bali/version.rb
- package.json
- spec/bali/components/sign_out_spec.rb
**Objetivo**
- Agregar componente `TurboNativeApp::SignOut`. Este componente permite cerrar sesión en `turbo native apps`
> Add `TurboNativeApp:SignOut` component

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/reveal/index.scss
- app/components/bali/reveal/preview.rb
- app/components/bali/reveal/previews/with_icon_and_title.html.erb
- app/components/bali/reveal/trigger/component.html.erb
- app/components/bali/reveal/trigger/component.rb
- lib/bali/version.rb
- package.json
- spec/bali/components/reveal_spec.rb
**Objetivo**
- Mostrar un ícono en el título del trigger
> Add title icon to reveal component

- CHANGELOG.md
- Gemfile.lock
- lib/bali/version.rb
- package.json
- yarn.lock
**Objetivo**
- Reparar error que se presenta al ejecutar `rails assets:precompile` en el `host application`
**Error**
**Documentación de titap**
> Add @tiptap/pm to package.json

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/table/component.html.erb
- app/components/bali/table/component.rb
- app/components/bali/table/index.scss
- lib/bali/version.rb
- package.json
- spec/dummy/app/assets/stylesheets/application.scss
**Objetivo**
- Habilitar la opción de `sticky headers` para el `Table::Component`
> Add table sticky headers

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/calendar/header/component.html.erb
- app/components/bali/calendar/header/component.rb
- app/components/bali/calendar/preview.rb
- lib/bali/version.rb
- package.json
**Objetivo**
- Enviar URL al Calendario para generar links
> Enviar URL al Calendario para generar links

- .vscode/settings.json
- CHANGELOG.md
- Gemfile.lock
- app/components/bali/locations_map/card/component.rb
- app/components/bali/locations_map/component.html.erb
- app/components/bali/locations_map/component.rb
- app/components/bali/locations_map/index.js
- app/components/bali/locations_map/index.scss
- app/components/bali/locations_map/preview.rb
- lib/bali/version.rb
- package.json
- spec/bali/components/locations_map_spec.rb
**Cambios**
- Agregar tarjetas a `LocationsMap::Component` para poder visualizar información más detallada de la dirección.
- Al dar click en el pin dentro del map se seleccionan todas las tarjetas que concuerden con las coordenadas del pin
> Added cards to locations maps

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/bulk_actions/action/component.html.erb
- app/components/bali/bulk_actions/action/component.rb
- app/components/bali/bulk_actions/component.html.erb
- app/components/bali/bulk_actions/component.rb
- app/components/bali/bulk_actions/index.js
- app/components/bali/bulk_actions/index.scss
- app/components/bali/bulk_actions/item/component.rb
- app/components/bali/bulk_actions/preview.rb
- app/javascript/bali/index.js
- lib/bali/version.rb
- package.json
- spec/bali/components/bulk_actions_spec.rb
- spec/dummy/app/assets/stylesheets/application.scss
- spec/dummy/app/javascript/application.js
**Objective**
- Add a component that enable us to double-click on multiple DOM elements, selecting them, and subsequently applying an action.
> Add bulk actions component

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/modal/index.js
- lib/bali/version.rb
- package.json
Issue example:
https://github.com/user-attachments/assets/759a1974-f4dc-4182-85d4-af717910eb29
Issue solved:
https://github.com/user-attachments/assets/c4e55f93-d54f-426d-9f73-c74c7d324ee7
> Fixed redirection issues when requesting a restricted modal

- CHANGELOG.md
- Gemfile.lock
- app/components/bali/table/bulk_action/component.rb
- app/components/bali/table/index.js
- app/components/bali/table/index.scss
- config/locales/view_components.es.yml
- lib/bali/version.rb
- package.json
https://github.com/user-attachments/assets/4037f9fb-46ec-4e0e-ae2b-faed152b25c6
> Table Bulk Actions: custom style and render modal on click
